<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<link href='/new.css' rel='stylesheet' type='text/css' />
<link href='/tables.css' rel='stylesheet' type='text/css' />
<link rel='shortcut icon' href='/favicon.ico' type='image/x-icon' />
<link rel='icon' href='/favicon.ico' type='image/x-icon' />
