</head>

<body>
<!-- Banner at page top -->
<div id='top_banner'>
<div id='top_left'></div>
<div id='top_center' class='head_1'>Call change ringing resources</div>
<div id='top_right'></div>
</div>

<!-- Menu Banner -->
<div id='menu_banner'>
<div id='menu_container'>
<div id='ul_end'></div>
<div id='unselected_tab'><a class='unselected' href='/index.php'>Home</a></div>
<div id='us_split'></div>
<div id='selected_tab'><a class='selected' href='/league/index.php'>League</a></div>
<div id='su_split'></div>
<div id='unselected_tab'><a class='unselected' href='/ladder/index.html'>Ladder</a></div>
<div id='uu_split'></div>
<div id='unselected_tab'><a class='unselected' href='/compositions/index.html'>Compositions</a></div>
<div id='ur_end'></div>
</div>
</div>